package com.santo.blm.model;

public enum CompetenceEnum {
	ADMINISTRATEUR, ARTISAN, ARTISTE, ATHLETE, BAGARREUR, BATELIER, BOUGEARD, BRICOLEUR, CITADIN, ECLAIREUR, ERUDIT,
	FERAILLEUR, GENTILHOMME, INTRIGANT, LARRON, MARCHAND, MEDECIN, ORATEUR, PAYSAN, SALTIMBANQUE, SOLDAT, TIREUR,
	VENEUR, VOYAGEUR, PORTEUR;
}
